version: '3.7'

services:
  summarization:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./backend
        target: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  streamlit:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    command: ["streamlit", "run", "app.py"]
